services:
    grafana:
        image: grafana/grafana-enterprise
        container_name: tpe-redes-grafana
        restart: unless-stopped
        ports:
        - '2000:3000'
        networks:
            - network
        environment:
            - GF_SMTP_ENABLED=true
            - GF_SMTP_HOST=smtp.gmail.com:587
            - GF_SMTP_USER=grafana.redes.itba@gmail.com
            - GF_SMTP_PASSWORD=$GF_SMTP_PASSWORD
            - GF_SMTP_SKIP_VERIFY=false
            - GF_SMTP_FROM_NAME=grafana
            - GF_SMTP_FROM_ADDRESS=grafana.redes.itba@gmail.com
        volumes:
            - ./grafana_data/provisioning:/etc/grafana/provisioning
            - ./grafana_data/dashboards:/var/lib/grafana/dashboards

    loki:
        image: grafana/loki:2.8.2
        container_name: tpe-redes-loki
        ports:
            - "3100:3100"
        volumes:
            - ./loki_data/loki-config.yml:/etc/loki/loki-config.yml
        command: -config.file=/etc/loki/loki-config.yml
        networks:
            - network

    prometheus:
        image: prom/prometheus
        container_name: tpe-redes-prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - network

networks:
    network:
        name: tpe-redes-network
        external: true
