global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['api:80']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']