global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['api:80']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]
  - job_name: 'mlflow_exporter'
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['uekbioiuv1.execute-api.us-east-1.amazonaws.com']