services:
    api:
        container_name: tpe-redes-api
        image: tpe-redes-api-image
        build:
            context: ./api
        ports:
            - 80:80
        networks:
            - network
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    db:
        container_name: tpe-redes-db
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        networks:
            - network
    frontend:
        container_name: tpe-redes-frontend
        image: tpe-redes-frontend-image
        build:
            context: ./frontend
        ports:
            - 3000:3000
        networks:
            - network
        environment:
            FLASK_ENV: development
            FLASK_APP: app/main.py
        command: flask run --host=0.0.0.0 --port=3000    

    postgres_exporter:
        container_name: tpe-redes-postgres-exporter
        image: prometheuscommunity/postgres-exporter
        environment:
        - DATA_SOURCE_NAME=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable
        ports:
        - 9187:9187
        networks:
        - network
        depends_on:
        - db
        
volumes:
    pgdata:
        driver: local
        driver_opts:
            o: "size=50m"
            device: tmpfs
            type: tmpfs

networks:
    network:
        driver: bridge
        name: tpe-redes-network
