services:
    api:
        container_name: tpe-redes-api
        image: tpe-redes-api-image
        build:
            context: ./api
        ports:
            - 80:80
        networks:
            - network
    db:
        container_name: tpe-redes-db
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        networks:
            - network

volumes:
    pgdata:

networks:
    network:
        driver: bridge
        name: tpe-redes-network
