services:
    api:
        container_name: tpe-redes-api
        image: tpe-redes-api-image
        build:
            context: ./api
        ports:
            - 80:80
    db:
        container_name: tpe-redes-db
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: