{
 "title": "DB Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "DB Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes) / (32 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"postgres\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "predict_linear(pg_database_size_bytes{datname=\"postgres\"}[5m], 5*60) + 0",
     "legendFormat": "Prediction"
    }
   ]
  }
 ]
}